name: 'Auto deploy to Dokku Main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1.0.1
        with:
          git_remote_url: 'ssh://dokku@fortnitefrance.eu:22/www'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
